<a href="https://colab.research.google.com/github/sivashobana547/Seeds-dataset-SVM-classification/blob/main/SEEDS_DATASET_USING_SVM_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import LabelEncoder
import gradio as gr
from sklearn import svm

In [ ]:
df=pd.read_csv('/content/seeds_dataset (2).csv')

In [ ]:
df

,Area,Perimeter,Compactness,Length of kernel,Width of kernel,Asymmetry coefficient,Length of kernel groove,"Class (1, 2, 3)",Unnamed: 8,Unnamed: 9
0,15.26,14.84,0.8710,5.763,3.312,2.221,5.220,1,NaN,NaN
1,14.88,14.57,0.8811,5.554,3.333,1.018,4.956,1,NaN,NaN
2,14.29,14.09,0.9050,5.291,3.337,2.699,4.825,1,NaN,NaN
3,13.84,13.94,0.8955,5.324,3.379,2.259,4.805,1,NaN,NaN
4,16.14,14.99,0.9034,5.658,3.562,1.355,5.175,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
205,12.19,13.20,0.8783,5.137,2.981,3.631,4.870,3,NaN,NaN
206,11.23,12.88,0.8511,5.140,2.795,4.325,5.003,3,NaN,NaN
207,13.20,13.66,0.8883,5.236,3.232,8.315,5.056,3,NaN,NaN
208,11.84,13.21,0.8521,5.175,2.836,3.598,5.044,3,NaN,NaN
209,12.30,13.34,0.8684,5.243,2.974,5.637,5.063,3,NaN,NaN

In [ ]:
x=df.iloc[:, 0:7]
y=df.iloc[:, 7:]

In [ ]:
x

,Area,Perimeter,Compactness,Length of kernel,Width of kernel,Asymmetry coefficient,Length of kernel groove
0,15.26,14.84,0.8710,5.763,3.312,2.221,5.220
1,14.88,14.57,0.8811,5.554,3.333,1.018,4.956
2,14.29,14.09,0.9050,5.291,3.337,2.699,4.825
3,13.84,13.94,0.8955,5.324,3.379,2.259,4.805
4,16.14,14.99,0.9034,5.658,3.562,1.355,5.175
...,...,...,...,...,...,...,...
205,12.19,13.20,0.8783,5.137,2.981,3.631,4.870
206,11.23,12.88,0.8511,5.140,2.795,4.325,5.003
207,13.20,13.66,0.8883,5.236,3.232,8.315,5.056
208,11.84,13.21,0.8521,5.175,2.836,3.598,5.044
209,12.30,13.34,0.8684,5.243,2.974,5.637,5.063

In [ ]:
y

     Class (1, 2, 3) Unnamed: 8 Unnamed: 9
0                  1        NaN        NaN
1                  1        NaN        NaN
2                  1        NaN        NaN
3                  1        NaN        NaN
4                  1        NaN        NaN
..               ...        ...        ...
205                3        NaN        NaN
206                3        NaN        NaN
207                3        NaN        NaN
208                3        NaN        NaN
209                3        NaN        NaN

[210 rows x 3 columns]

In [ ]:
df.isnull().sum()

Area                         0
Perimeter                    0
Compactness                  0
Length of kernel             0
Width of kernel              0
Asymmetry coefficient        0
Length of kernel groove      0
Class (1, 2, 3)              0
Unnamed: 8                 208
Unnamed: 9                 209
dtype: int64

In [ ]:
df.drop(columns=['Unnamed: 8'], inplace=True)

In [ ]:
df.drop(columns=['Unnamed: 9'], inplace=True)

In [ ]:
x_train, x_test, yec_train, yec_test = train_test_split(x, yec, test_size=0.2, random_state=42)


model = svm.SVC(kernel='linear')

In [ ]:
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print(y_pred)
acc = accuracy_score(y_test, y_pred)